### ISSUE TITLE
Traducción de workflow

### ISSUE THREAD

**Issue by bodypheo** [progit/progit2-es#11]
Hola, en algunos puntos creo que queda mejor modo de trabajo en lugar de flujo de trabajo, dependiendo del contexto. Por ejemplo:

>Si ya estás cómodo usando un flujo de trabajo centralizado en tu equipo o en tu empresa puedes >continuar usando ese modo de trabajo.
El original
>If you are already comfortable with a centralized workflow in your company or team, you can easily >continue using that workflow with Git.

¿Mantengo flujo de trabajo en ambos?
¿Opiniones?

Gracias

**Comment by andres-mancera** [comment]
Estoy de acuerdo.  Me parece que "_modo de trabajo_" funciona mejor en este caso.
¡Gracias @bodypheo !

**Comment by andres-mancera** [comment]
Voy a cerrar este "issue" debido a que no ha tenido ninguna actividad por 6 meses. Saludos.
