### ISSUE TITLE
Compilation to PDF and epub

### ISSUE THREAD

**Issue by jnavila** [progit/progit2-es#112]
Hi all,

I'm in the process of making an automatic publication of the book on git-scm.com, using asciidoctor and Travis-CI for generating the PDF and epub. That should solve #56 .

This rework requires to move files around, change how cross-refs are done and change build script. This is quite disruptive and would cause conflicts with ongoing changes. 

Please ping me when the repo is idle, so that I can make the transition before you guys restart your work.

Thanks,

**Comment by jnavila** [comment]
Ping @andres-mancera

**Comment by andres-mancera** [comment]
@jnavila : Quick Question: Has this new flow for the automatic publication of the book been enabled for any language or even the original English version?

**Comment by jnavila** [comment]
Yes, it has. You can see the result on https://git-scm.com/book . For all the translations with this workflow, there are the availability to download the books in pdf, epub and mobi files.
![image](https://user-images.githubusercontent.com/156172/37700650-9cdc2f18-2cec-11e8-8324-677a88982ad2.png)

**Comment by andres-mancera** [comment]
Ok, I don't have any pending pull request right now, so please go ahead and make the required changes.  Let me know if you need anything from me.  Thanks @jnavila 👍

**Comment by jnavila** [comment]
Just a heads up to indicate that the book is not compiling right now. This is mostly due to remains of conflicts marks that weren't removed.

**Comment by andres-mancera** [comment]
Is there some kind of log that I can take a look at so that we can fix the issues(s)?
Otherwise, we'll be trying to find a needle in a haystack!

**Comment by jnavila** [comment]
Don't worry, I'm on it. The ugly thing about it is that the errors of compilation don't point to the place where the mistake was made, but where the parser can no longer cope with the errors. The branch should be ready before this week end.

**Comment by andres-mancera** [comment]
Great, thanks a lot for your help @jnavila 😃

**Comment by andres-mancera** [comment]
@jnavila : After your [changes](https://github.com/progit/progit2-es/commit/da4ab7fbc4b4c11120a5b3abc76d4eee2e669d4f#diff-3c63e35dcfd53b9b21c01c0d5ab7c35b), I see that the "contributors.asc" file now has a link to a file called "contributors.txt".  However, I don't see that file anywhere.  Where did the list of contributors go?

**Comment by jnavila** [comment]
The file `contributors.txt` is now dynamically created by the Rakefile
  
https://github.com/progit/progit2-es/blob/b665495e2470316d112ac4365680e422c2d02688/Rakefile#L46-L47

It is always up to date with the correct list of contributors. You can run the command line in order to generate it for yourself, without requiring the full ruby environment.

**Comment by andres-mancera** [comment]
I see.  Thanks @jnavila 👍
