### ISSUE TITLE
Spanish lang?

### ISSUE THREAD

**Issue by Alexey-T** [progit/progit2-es#124]
Hi, can you pls, help with Spanish lang for CudaText? thanks.

**Comment by andres-mancera** [comment]
Hello @Alexey-T .  Not sure what you are asking for.  Can you please elaborate a bit more on your request to see if I can help you or at least point you in the right direction?

**Comment by Alexey-T** [comment]
I mean that CudaText editor is missing Spanish translation, maybe you can help.

**Comment by andres-mancera** [comment]
Is that project hosted here in GitHub?  If so, can you pls send me a pointer to it?

**Comment by Alexey-T** [comment]
Yes, on GitHub.
Pointers:
https://github.com/Alexey-T/CudaText
http://wiki.freepascal.org/CudaText
http://wiki.freepascal.org/CudaText#How_to_make_translation

**Comment by Gabriel-O-97** [comment]
Hello  came across this issue and was wondering if you still needed help translating your [http://wiki.freepascal.org/CudaText#How_to_make_translation] section?

> Yes, on GitHub.
> Pointers:
> https://github.com/Alexey-T/CudaText
> http://wiki.freepascal.org/CudaText
> http://wiki.freepascal.org/CudaText#How_to_make_translation

i would love to contribute 💯

**Comment by Alexey-T** [comment]
Hi. I mean translate the CudaText program UI, not the wiki section...

**Comment by andres-mancera** [comment]
Closing this issue as this was actually a request for some help in another Spanish translation project.  Cheers!
