### ISSUE TITLE
Traducción incompleta 5.1 Git en entornos distribuidos - Flujos de trabajo distribuidos

### ISSUE THREAD

**Issue by einsteinyh** [progit/progit2-es#127]
Hola.

Soy novato con Git y leyendo la documentación en línea [encontré este capítulo](https://git-scm.com/book/es/v2/Git-en-entornos-distribuidos-Flujos-de-trabajo-distribuidos#ch05-distributed-git) traducido en un 40% o 50%.

Creo este ¿incidente? para que se pueda llevar un seguimiento, si bien hasta no tener algo más de experiencia, y comprender cómo está organizado el repositorio (y en general Git) a cabalidad, no me ofrezco a realizar la traducción yo mismo.

Nota: Se que hay un incidente abierto previamente para este capítulo y cerrado por inactividad, abro otro al no tener claro si es posible reabrirlo. (https://github.com/progit/progit2-es/issues/32) 

Muchas gracias por el trabajo realizado, ayuda bastante leer la documentación en español de esta herramienta.

Saludos.

**Comment by andres-mancera** [comment]
Gracias @einsteinyh y adelante con la traduccción de ese capitulo.  Por favor envia tu pull request tan pronto hayas terminado tu trabajo.  No tienes que esperas hasta que este finalizado en un 100%.  Lo puedes hacer de forma incremental.  Saludos.

**Comment by juanpflores** [comment]
Hey @einsteinyh @andres-mancera 👋 
Si quieres me encargo de hacer la traducción del capitulo, a menos de que haya alguien más haciendolo

**Comment by einsteinyh** [comment]
Hola. Por supuesto, te agradecería mucho el esfuerzo :D. Apenas tenga la posibilidad yo empezaría con alguno de los que están pendientes.

**Comment by andres-mancera** [comment]
@einsteinyh y @juanpflores : Son bienvenidos a seguir colaborando en este proyecto!
Voy a cerrar este "issue" ahora.  Saludos.
