### ISSUE TITLE
Translation is off

### ISSUE THREAD

**Issue by Gabriel-O-97** [progit/progit2-es#129]
Hi i was having a read through your project pages, and saw that there are a few errors with the Spanish dialect, and i was wondering if i could help out by fixing these errors?
'first-time-setup.asc' translation is off in this section

https://github.com/progit/progit2-es/blob/master/book/01-introduction/sections/first-time-setup.asc

**Comment by andres-mancera** [comment]
Hi @Gabriel-O-97 .  Sure!!!  Please help us out and fix any issues you might come across as you go over the translation!  This is an open-source project, so contributions from the community are always welcome.  That's how we improve the the final product.  😄

**Comment by Gabriel-O-97** [comment]
Hello @andres-mancera Just to let you know i have submitted a few solutions to come issues i found, very happy to have contributed to your project 😄 
Gracias por darme la oportunidad de ser parte de tu projecto

**Comment by andres-mancera** [comment]
Gracias @Gabriel-O-97 ! 👍
