### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by douglasmoraes** [progit/progit2-es#132]
Good afternoon,

My name is Douglas and i want to help translate Pro Git book, in fact i already translated some parts. 

But i cannot find the portugues project, like i found in spanish.

How can i commit for the portuguese version of this book?

**Comment by andres-mancera** [comment]
Hi @douglasmoraes .  Please take a look at [this issue](https://github.com/progit/progit2/issues/243), which will show you how I got started with the Spanish version.  Hope this helps!

**Comment by jnavila** [comment]
Hi, as noted [here](https://github.com/progit/progit2/blob/master/TRANSLATING.md), the brazilian translation project is already running at https://github.com/progit2-pt-br/progit2 . It's not very lively, but you can maybe give a hand there.

**Comment by andres-mancera** [comment]
Thanks for chiming in @jnavila .  Given that this was just a question and not really a problem with the Spanish translation project, I am closing this issue now.
