### ISSUE TITLE
The Spanish translation has some errors

### ISSUE THREAD

**Issue by DiegoFRamirez** [progit/progit2-es#135]
Hello community.
I'm Git user, and speak native Spanish language. But, sorry. My English is not very good.
I'm read the last edition book Pro Git (in Spanish), and I see errors traduction. Not very important, but errors finally. I would like to contribute with corrections (if this is possible). I do not want to be disrespectful. Mostly I have seen small typographical and syntax errors.
I'm wait for your response for start this task. And last time send the result for compare and aprove (or not) the changes and corrections.
Thanks for read!!
Sincerily,
Diego Ramírez.

**Comment by andres-mancera** [comment]
Hola @DiegoFRamirez .  Tu ayuda es bienvenida!  Si encuentras errores en la traduccion, por favor has un "pull request" y yo lo reviso/apruebo.  Gracias de antemano por tu ayuda!  Saludos.

**Comment by DiegoFRamirez** [comment]
Hola @andres-mancera. Gracias por permitirme contribuir. Haré un fork y comenzaré a trabajar. Como comentaba (de manera tosca en mi débil inglés), son en general pequeños errores de sintaxis o de ortografía. Nada que impida entender perfectamente la guía. Pero, bueno, son errores y les agradezco que me permitan ayudar a corregirlos.

**Comment by andres-mancera** [comment]
Espero tu "pull request" @DiegoFRamirez !  Saludos.
