### ISSUE TITLE
Error de traducción de una nota 

### ISSUE THREAD

**Issue by javierbrk** [progit/progit2-es#153]
https://www.git-scm.com/book/es/v2/Fundamentos-de-Git-Deshacer-Cosas

**La nota dice** _"A pesar de que git reset puede ser un comando peligroso si lo llamas con --hard, en este caso el archivo que está en tu directorio de trabajo no se toca. Ejecutar git reset sin opciones no es peligroso - solo toca el área de preparación."_

**debería decir** "git reset puede ser un comando peligroso espcialmente si lo llamas con la opción --hard. Sin embargo en el escenario descripto anteriormente, el archivo que está en tu directorio de trabajo no se toca. Ejecutar git reset sin opciones no es peligroso - solo toca el área de preparación."

**version en inglés** _"It’s true that git reset can be a dangerous command, especially if you provide the --hard flag. However, in the scenario described above, the file in your working directory is not touched, so it’s relatively safe."_

**Comment by Arnau-Ninerola** [comment]
Voy a arreglar esto en un pull request.

**Comment by andres-mancera** [comment]
@javierbrk , gracias por tu comentario.

@Arnau-Ninerola : Acabo de hacer "merge" a tu pull request #154.  Muchas gracias por tu colaboracion.
