### ISSUE TITLE
Colaborar

### ISSUE THREAD

**Issue by andrescabrera** [progit/progit2-es#19]
Hola, quería saber como puedo empezar a colaborar con la traducción.
No soy especialista ni traductor oficial, simplemente un usuario técnico.

Saludos.-

**Comment by andres-mancera** [comment]
Hola Andrés:  Perdona la demora en mi respuesta.  Prometo responderte más rápido en futuras ocasiones.  Puedes ayudar con la traducción de la forma en que tú lo desees.  Hay algunos capítulos que ya han sido traducidos por otras personas.  De la misma manera, hay algunos capítulos que no han empezado a ser traducidos.  Puedes escoger cualquiera y hacer las ediciones respectivas.  Te recomiendo hacerle "fork" al repositorio y crear un "branch".  Debes hacer todo tu trabajo en el branch (tal y como lo harías en cualquier proyecto open source).  Cuando estés listo, puedes sencillamente hacer un "pull request".  Avísame por favor si tienes preguntas adicionales.  Saludos.

**Comment by fizzvr** [comment]
Como dice el compañero primero hacerle Fork :fork_and_knife: 
https://github.com/progit/progit2-es/blob/master/README.asc#cómo-generar-el-libro

**Comment by andres-mancera** [comment]
Voy a cerrar este "issue" debido a que no ha tenido ninguna actividad por 4 meses. Espero sus contribuciones.  Saludos.
