### ISSUE TITLE
Traducción de 05-distributed-git/sections/maintaining.asc

### ISSUE THREAD

**Issue by jcarlosgarcia** [progit/progit2-es#24]
Buenas,
    Voy a comenzar a trabajar en la traducción de esta sección, según el status.json está al 0%.

Saludos.

**Comment by fizzvr** [comment]
:+1:

**Comment by andres-mancera** [comment]
Hola José Carlos.  Sigo a la espera de tu "pull request".  :sunglasses:

**Comment by jcarlosgarcia** [comment]
Buenas Andrés,

Estoy en ello, ando con mucho lío últimamente...

Saludos

**Comment by andres-mancera** [comment]
No hay problema, José Carlos.  ¡Gracias por tu ayuda!

**Comment by andres-mancera** [comment]
"Pull request" aceptado.  ¡Gracias nuevamente @jcarlosgarcia !
