### ISSUE TITLE
Secciones en inglés en la página del libro

### ISSUE THREAD

**Issue by moisesroj0** [progit/progit2-es#29]
¿Por qué hay secciones en inglés en ciertas partes del libro en la página oficial?

[1.1 Inicio - Sobre el Control de Versiones - Acerca del Control de Versiones](https://git-scm.com/book/es/v2/Inicio---Sobre-el-Control-de-Versiones-Acerca-del-Control-de-Versiones)

    -Figure 1-1. Local version control.
    -Centralized version control diagram
        Figure 1-2. Centralized version control.
    -Figure 1-3. Distributed version control.

¿Por qué no poner estos tres conjuntos de palabras en español?

[1.5 Inicio - Sobre el Control de Versiones - Instalación de Git](https://git-scm.com/book/es/v2/Inicio---Sobre-el-Control-de-Versiones-Instalaci%C3%B3n-de-Git)
Justo empezado dice "NOTE" y en el código está como "[NOTE]" al estar entre paréntesis no he movido nada, pero... si no veo que sea alguna referencia, más que tal vez a que el archivo cree una vista de "nota"

**Comment by moisesroj0** [comment]
Ya vi que el texto de  algunas "Figure"s ha sido traducido así que también he traducido otras, la cuestión ahora es las "NOTE"s espero, algún administrador del proyecto esté atento.

**Comment by andres-mancera** [comment]
@moisesroj0 : Hay secciones del libro que todavía aparecen en inglés porque el libro no ha sido traducido en su totalidad.  ¡Tus contribuciones son bienvenidas!  Saludos.
