### ISSUE TITLE
Traducción de "non-fast forward"

### ISSUE THREAD

**Issue by moisesroj0** [progit/progit2-es#31]
No estoy seguro de que traducción pueda ser la más correcta ocupar, sería más sencillo si se llamara "avance lento" desde el programa, pero no estoy seguro de que traducción ocupar para mantener lo mejor posible el estilo de versión original.

[5 Flujos de trabajo distribuidos](https://git-scm.com/book/es/v2/Git-en-entornos-distribuidos-Flujos-de-trabajo-distribuidos)

> She is told that she's trying to push non-fast-forward changes and that she won't be able to do so until she fetches and merges.
> 
> Se le dice a ella que está tratando de empujar cambios **de avance no rápido** y que no va a ser capaz de hacerlo hasta que recupere y se fusione.

_La traducción es rápida, no final._

**Comment by ezefarina** [comment]
Tal vez en vez de utilizar el término "non-fast-forward" se podría considerar como "recursive strategy", lo que en términos de estrategia de merge sería lo opuesto

**Comment by andres-mancera** [comment]
@moisesroj0 : Dejo en tus manos la decisión final acerca de qué traducción es más correcta.  Lo único que te podría aconsejar es dejar el término original en inglés entre paréntesis.  ¿Te parece bien?

**Comment by andres-mancera** [comment]
Voy a cerrar este "issue" debido a que no ha tenido actividad en el último año.  Saludos.
