### ISSUE TITLE
Traducción de 05-distributed-git/sections/distributed-workflows.asc

### ISSUE THREAD

**Issue by ezefarina** [progit/progit2-es#32]
Voy a estar traduciendo la sección 05-distributed-git/sections/distributed-workflows.asc, la cual se encuentra en master con un 10% comenzado pero se muestra en 0% en status.json. No estoy seguro de si alguien la comenzó y abandonó o si realmente alguien está trabajando en esa. If not, then I'm on it :)

**Comment by andres-mancera** [comment]
Todo tuyo @ezefarina , ¡muchas gracias de antemano!

**Comment by andres-mancera** [comment]
Voy a cerrar este "issue" debido a que no ha tenido actividad en el último año.  Saludos.
