### ISSUE TITLE
Traducción de Prefacios

### ISSUE THREAD

**Issue by jamj2000** [progit/progit2-es#33]
Hola Andrés,
me he unido al grupo de traducción. 

Esta semana dispongo de algo de tiempo. Me gustaría empezar a traducir algo sencillito, los Prefacios.

**Comment by andres-mancera** [comment]
Bienvenido @jamj2000 !  Acabo de aceptar to pull request #34 .  Gracias nuevamente.  :+1:

**Comment by andres-mancera** [comment]
Voy a cerrar este "issue" ahora.  Saludos.
