### ISSUE TITLE
Traducción de Apéndice C

### ISSUE THREAD

**Issue by jamj2000** [progit/progit2-es#39]
Voy a empezar también la traducción del Apéndice C.

**Comment by andres-mancera** [comment]
Voy a cerrar este "issue" debido a que el pull request #42 ya ha sido aceptado.
Saludos.

**Comment by jamj2000** [comment]
OK, lo cierro yo. Estaba aún abierto ;)

**Comment by andres-mancera** [comment]
¡Ops!   Gracias.  :smile:
