### ISSUE TITLE
Traducción del Capítulo 10

### ISSUE THREAD

**Issue by jamj2000** [progit/progit2-es#43]
He observado que el capítulo 10 es prácticamente igual al capítulo 9 de la versión anterior de Pro Git, así que me he animado a realizar la traducción.

Tardaré un poquito, pero en ello estoy por si es de interés.

Un saludo.

**Comment by andres-mancera** [comment]
Voy a cerrar este "issue" debido a que el pull request #45 ha sido aceptado.  Saludos.
