### ISSUE TITLE
Contenido desactualizado, correcciones no aplicadas. 

### ISSUE THREAD

**Issue by Pablohn26** [progit/progit2-es#50]
He llegado aquí porque quería corregir un par de faltas de ortografía en [este capítulo](https://git-scm.com/book/es/v1/Git-en-un-servidor-Generando-tu-clave-p%C3%BAblica-SSH), sin embargo veo que el contenido no se corresponde con el artículo de [este repositorio](https://github.com/progit/progit2-es/blob/master/book/04-git-server/sections/generating-ssh-key.asc). Por ejemplo las correcciones de 613dacc33ea0ec35fb0c2f2958ae9f8e663ab47f no están aplicadas. ¿Alguien sabe por qué puede ser esto?

**Comment by fizzvr** [comment]
Pienso que es por que el administrador que tiene acceso al dominio _://git-scm.com_ tiene que re compilar la fuente, cosa que no ocurre todavía yo tengo mezclado un cambio a8b78b7cb706efb55bd4421d110c00992f1f859f el cual todavía no se a compilado, por lo tanto tenemos en este repositorio la versión más actual, además faltan secciones por traducir.

**Comment by andres-mancera** [comment]
Hola @Pablohn26 , @fizzvr :  En este momento tenemos un problema con el proceso de "build" del libro:  Estabamos utilizando la plataforma Atlas de O'Reilly, pero esa plataforma ha sido descontinuada.  Los administradores estamos contemplando otras posiblidades - hay un "issue" abierto para hacerle seguimiento a este problema:  [#625](https://github.com/progit/progit2/issues/625).

**Comment by fizzvr** [comment]
Hola @andres-mancera el cambio ya se ve reflejado, y al parecer todo está normal. En cambio @Pablohn26 acabo de darme cuenta que los cambios no se ven reflejados por que tú estas viendo el link de la version 1, en el link de la [v2](https://git-scm.com/book/es/v2/Git-en-el-Servidor-Generando-tu-clave-p%C3%BAblica-SSH) los cambios si se ven reflejados.

**Comment by fizzvr** [comment]
A colaborar.... CLOSE this issue. :+1:

**Comment by andres-mancera** [comment]
Gracias @fizzvr y @Pablohn26 .  Saludos.
