### ISSUE TITLE
Traducción del Capitulo 7

### ISSUE THREAD

**Issue by pilarArr** [progit/progit2-es#54]
Hola me gustaría colaborar con la traducción, he visto que falta el capitulo 7. Si no hay nadie trabajando con el puedo empezar yo. Tengo que hacer un fork y un brach para empezar a trabajar ¿no?, ¿los commits los hago cada capítulo o tenéis algún otro sistema establecido?

**Comment by pilarArr** [comment]
Hola @andres-mancera, he visto que sueles responder a los Issues. ¿Que opinas de que me ponga con el capítulo 7?

**Comment by andres-mancera** [comment]
Hola @pilarArr .  La forma de contribuir es básicamente la misma que se sigue en cualquier otro proyecto "open source".  Te recomiendo revisar la [página](https://github.com/progit/progit2-es/blob/master/TRANSLATION_NOTES.asc) en donde explico la forma correcta de hacerlo.  :smile: 

¡Adelante con el capítulo 7!  Espero tu "pull request"....

**Comment by andres-mancera** [comment]
Hola @pilarArr : Estoy pensando en cerrar este "issue" debido a que tu pull request #55 ya fue aceptado.  ¿Está bien por ti?

**Comment by pilarArr** [comment]
Hola @andres-mancera,
Pues es que el pull request es solo del glosario de terminos, he estado traduciendo algunos apartados del capitulo 7 (que es de lo que iba el issue), llevo como 6 archivos. No he tenido mucho tiempo ultimamente, pero tengo intencion de terminarlo. De todas maneras si lo quieres cerrar esta bien, o podria hacer un pull request de lo que llevo hecho hasta ahora.

**Comment by andres-mancera** [comment]
Hola @pilarArr :  Por el momento voy a cerrar este "issue" entonces.  Me avisas cuando estés lista para realizar tu "pull request".  Gracias por tu ayuda.  Saludos.
