### ISSUE TITLE
¿Dónde están los libros (epub/pdf) para descargar?

### ISSUE THREAD

**Issue by disalinas** [progit/progit2-es#56]
Hola. Estoy buscando el libro en castellano para descargarlo en pdf o epub. Pero no lo encuentro por ningún lugar. En la versión en inglés está en releases, pero aquí no hay nada. Además, en el readme se indica claramente que tiene que haber alguna versión "compilada".

> La manera más fácil es simplemente dejando que nosotros lo hagamos. Tenemos un robot que detecta cualquier contribución nueva en la rama principal (main branch) y genera el libro automáticamente para todos.

**Comment by andres-mancera** [comment]
Hola.  Puedes encontrar el libro y todas sus traducciones aquí:
https://git-scm.com/book/en/v2

**Comment by disalinas** [comment]
Hola. Eso es el libro online y ahí, al menos yo, no he encontrado ningún enlace de descarga del libro en castellano, ya sea en PDF o en EPUB. Y me gustaría poder llevarlo OFFLINE en la tablet o en el libro electrónico. Sí en la web de Git hay enlaces de descarga del libro en castellano como indican aquí, por favor, dime donde, pero no me pongas la documentación online.

**Comment by andres-mancera** [comment]
Hola @disalinas .  Hasta hace un tiempo la versión PDF de las diferentes traducciones se podía encontrar en la página principal.  No me había percatado de que ahora no es así.  Aquí te dejo un [link](https://github.com/progit/progit2/issues/747) a un "issue" acerca de este tema.  Tienes 2 opciones:  Descargar la versión de nuestra traducción hasta 2017/05/01, o generar tu propia copia con el comando `asciidoctor-pdf`.

**Comment by borekon** [comment]
He clonado el repo para añadirlos a release, ya que no sé cómo hacerlo en el repo principal.
Te dejo el [enlace](https://github.com/borekon/progit2-es/releases)
