### ISSUE TITLE
Traducciones al Español (pregunta)

### ISSUE THREAD

**Issue by vacilagodzila** [progit/progit2-es#72]
Saludos, estoy interesado en contribuir con traducciones. **Sólo quería saber si el repo sigue activo** y recibiendo pull requests ya que puedo ver que aún faltan por traducir algunos archivos.

¡Gracias!

**Comment by andres-mancera** [comment]
Hola @vacilagodzila .  El repo sigue activo y continuo recibiendo "pull requests", así que tu colaboración sera bienvenida.  Saludos.
