### ISSUE TITLE
¿Es posible hacer una build en Linux?

### ISSUE THREAD

**Issue by nanotime** [progit/progit2-es#8]
Pues es la pregunta, no tengo acceso a OSX y hasta donde entiendo, bundle es una herramienta de ese sistema... ¿Existe alguna manera de hacer un build en Linux?

**Comment by nanotime** [comment]
Fe de errata, confundí por un momento bundle con brew. Perdon por la confusión, no estoy familiarizado con esta herramienta.

**Comment by andres-mancera** [comment]
@nanotime : Efectivamente es posible hacer un "build" del libro en Linux.  La forma de hacerlo está explicada en el [README.asc](https://github.com/progit/progit2-es/blob/master/README.asc).  Yo jamás he generado el libro por mi cuenta.  Sencillamente realizo los "commits" y dejo que el script se encargue de generar la versión actualizada del libro.

**Comment by jjamor** [comment]
Yo estoy utilizando un docker:

https://registry.hub.docker.com/u/asciidoctor/docker-asciidoctor/

es una forma rápida de tener en Linux el entorno necesario para generar el libro y comprobar que
no tiene errores de Asciidoctor.

En una ubuntu es casi tan simple como instalar docker (apt-get install docker.io)
y luego bajarte la imagen (docker pull asciidoctor/docker-asciidoctor)

Te vas al directorio del proyecto y haces:

```
$ docker run -it -v $PWD:/documents asciidoctor/docker-asciidoctor
```

Ahora en /documents puedes ejecutar asciidoctor para generar el libro:

```
# cd /documents
# asciidoctor progit.asc
# asciidoctor-pdf progit.asc
. . .
```

Por si a alguien le resulta útil ;-)

**Comment by nanotime** [comment]
Se ve interesante, jamás he usado Docker pero puedo empezar. ¡Gracias!

**Comment by andres-mancera** [comment]
Voy a cerrar este "issue" debido a que no ha tenido ninguna actividad por 6 meses.  Saludos.
